/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RentalPointsRouteImport } from './routes/rental-points'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LiveShiftsRouteImport } from './routes/live-shifts'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBokunWebhookRouteImport } from './routes/api/public/bokun-webhook'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalPointsRoute = RentalPointsRouteImport.update({
  id: '/rental-points',
  path: '/rental-points',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveShiftsRoute = LiveShiftsRouteImport.update({
  id: '/live-shifts',
  path: '/live-shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBokunWebhookRoute = ApiPublicBokunWebhookRouteImport.update({
  id: '/api/public/bokun-webhook',
  path: '/api/public/bokun-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/notifications': typeof NotificationsRoute
  '/rental-points': typeof RentalPointsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/api/public/bokun-webhook': typeof ApiPublicBokunWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/notifications': typeof NotificationsRoute
  '/rental-points': typeof RentalPointsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/api/public/bokun-webhook': typeof ApiPublicBokunWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/notifications': typeof NotificationsRoute
  '/rental-points': typeof RentalPointsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/api/public/bokun-webhook': typeof ApiPublicBokunWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/live-shifts'
    | '/notifications'
    | '/rental-points'
    | '/reset-password'
    | '/shifts'
    | '/staff'
    | '/tasks'
    | '/api/public/bokun-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/live-shifts'
    | '/notifications'
    | '/rental-points'
    | '/reset-password'
    | '/shifts'
    | '/staff'
    | '/tasks'
    | '/api/public/bokun-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/live-shifts'
    | '/notifications'
    | '/rental-points'
    | '/reset-password'
    | '/shifts'
    | '/staff'
    | '/tasks'
    | '/api/public/bokun-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  LiveShiftsRoute: typeof LiveShiftsRoute
  NotificationsRoute: typeof NotificationsRoute
  RentalPointsRoute: typeof RentalPointsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShiftsRoute: typeof ShiftsRoute
  StaffRoute: typeof StaffRoute
  TasksRoute: typeof TasksRoute
  ApiPublicBokunWebhookRoute: typeof ApiPublicBokunWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-points': {
      id: '/rental-points'
      path: '/rental-points'
      fullPath: '/rental-points'
      preLoaderRoute: typeof RentalPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-shifts': {
      id: '/live-shifts'
      path: '/live-shifts'
      fullPath: '/live-shifts'
      preLoaderRoute: typeof LiveShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bokun-webhook': {
      id: '/api/public/bokun-webhook'
      path: '/api/public/bokun-webhook'
      fullPath: '/api/public/bokun-webhook'
      preLoaderRoute: typeof ApiPublicBokunWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  LiveShiftsRoute: LiveShiftsRoute,
  NotificationsRoute: NotificationsRoute,
  RentalPointsRoute: RentalPointsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShiftsRoute: ShiftsRoute,
  StaffRoute: StaffRoute,
  TasksRoute: TasksRoute,
  ApiPublicBokunWebhookRoute: ApiPublicBokunWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
