/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RentalPointsRouteImport } from './routes/rental-points'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LiveShiftsRouteImport } from './routes/live-shifts'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BokunRunsRouteImport } from './routes/bokun-runs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWaiverForeverWebhookRouteImport } from './routes/api/public/waiver-forever-webhook'
import { Route as ApiPublicHooksSyncBokunRouteImport } from './routes/api/public/hooks/sync-bokun'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalPointsRoute = RentalPointsRouteImport.update({
  id: '/rental-points',
  path: '/rental-points',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveShiftsRoute = LiveShiftsRouteImport.update({
  id: '/live-shifts',
  path: '/live-shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BokunRunsRoute = BokunRunsRouteImport.update({
  id: '/bokun-runs',
  path: '/bokun-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaiverForeverWebhookRoute =
  ApiPublicWaiverForeverWebhookRouteImport.update({
    id: '/api/public/waiver-forever-webhook',
    path: '/api/public/waiver-forever-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncBokunRoute = ApiPublicHooksSyncBokunRouteImport.update({
  id: '/api/public/hooks/sync-bokun',
  path: '/api/public/hooks/sync-bokun',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bokun-runs': typeof BokunRunsRoute
  '/calendar': typeof CalendarRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/notifications': typeof NotificationsRoute
  '/payouts': typeof PayoutsRoute
  '/rental-points': typeof RentalPointsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/api/public/waiver-forever-webhook': typeof ApiPublicWaiverForeverWebhookRoute
  '/api/public/hooks/sync-bokun': typeof ApiPublicHooksSyncBokunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bokun-runs': typeof BokunRunsRoute
  '/calendar': typeof CalendarRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/notifications': typeof NotificationsRoute
  '/payouts': typeof PayoutsRoute
  '/rental-points': typeof RentalPointsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/api/public/waiver-forever-webhook': typeof ApiPublicWaiverForeverWebhookRoute
  '/api/public/hooks/sync-bokun': typeof ApiPublicHooksSyncBokunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bokun-runs': typeof BokunRunsRoute
  '/calendar': typeof CalendarRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/notifications': typeof NotificationsRoute
  '/payouts': typeof PayoutsRoute
  '/rental-points': typeof RentalPointsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/api/public/waiver-forever-webhook': typeof ApiPublicWaiverForeverWebhookRoute
  '/api/public/hooks/sync-bokun': typeof ApiPublicHooksSyncBokunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bokun-runs'
    | '/calendar'
    | '/live-shifts'
    | '/notifications'
    | '/payouts'
    | '/rental-points'
    | '/reset-password'
    | '/shifts'
    | '/staff'
    | '/tasks'
    | '/users'
    | '/api/public/waiver-forever-webhook'
    | '/api/public/hooks/sync-bokun'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bokun-runs'
    | '/calendar'
    | '/live-shifts'
    | '/notifications'
    | '/payouts'
    | '/rental-points'
    | '/reset-password'
    | '/shifts'
    | '/staff'
    | '/tasks'
    | '/users'
    | '/api/public/waiver-forever-webhook'
    | '/api/public/hooks/sync-bokun'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bokun-runs'
    | '/calendar'
    | '/live-shifts'
    | '/notifications'
    | '/payouts'
    | '/rental-points'
    | '/reset-password'
    | '/shifts'
    | '/staff'
    | '/tasks'
    | '/users'
    | '/api/public/waiver-forever-webhook'
    | '/api/public/hooks/sync-bokun'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BokunRunsRoute: typeof BokunRunsRoute
  CalendarRoute: typeof CalendarRoute
  LiveShiftsRoute: typeof LiveShiftsRoute
  NotificationsRoute: typeof NotificationsRoute
  PayoutsRoute: typeof PayoutsRoute
  RentalPointsRoute: typeof RentalPointsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShiftsRoute: typeof ShiftsRoute
  StaffRoute: typeof StaffRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
  ApiPublicWaiverForeverWebhookRoute: typeof ApiPublicWaiverForeverWebhookRoute
  ApiPublicHooksSyncBokunRoute: typeof ApiPublicHooksSyncBokunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-points': {
      id: '/rental-points'
      path: '/rental-points'
      fullPath: '/rental-points'
      preLoaderRoute: typeof RentalPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-shifts': {
      id: '/live-shifts'
      path: '/live-shifts'
      fullPath: '/live-shifts'
      preLoaderRoute: typeof LiveShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokun-runs': {
      id: '/bokun-runs'
      path: '/bokun-runs'
      fullPath: '/bokun-runs'
      preLoaderRoute: typeof BokunRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waiver-forever-webhook': {
      id: '/api/public/waiver-forever-webhook'
      path: '/api/public/waiver-forever-webhook'
      fullPath: '/api/public/waiver-forever-webhook'
      preLoaderRoute: typeof ApiPublicWaiverForeverWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-bokun': {
      id: '/api/public/hooks/sync-bokun'
      path: '/api/public/hooks/sync-bokun'
      fullPath: '/api/public/hooks/sync-bokun'
      preLoaderRoute: typeof ApiPublicHooksSyncBokunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BokunRunsRoute: BokunRunsRoute,
  CalendarRoute: CalendarRoute,
  LiveShiftsRoute: LiveShiftsRoute,
  NotificationsRoute: NotificationsRoute,
  PayoutsRoute: PayoutsRoute,
  RentalPointsRoute: RentalPointsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShiftsRoute: ShiftsRoute,
  StaffRoute: StaffRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
  ApiPublicWaiverForeverWebhookRoute: ApiPublicWaiverForeverWebhookRoute,
  ApiPublicHooksSyncBokunRoute: ApiPublicHooksSyncBokunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
